[2024-08-07T14:54:05.371+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-07T14:54:05.441+0000] {taskinstance.py:2066} INFO - Dependencies not met for <TaskInstance: airflow-space-exploration.notify_analysts manual__2024-08-07T14:20:08.695612+00:00 [queued]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'Ver_data'}
[2024-08-07T14:54:05.450+0000] {local_task_job_runner.py:163} INFO - Task is not able to be run
[2024-08-07T14:55:34.635+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-07T14:55:34.675+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow-space-exploration.notify_analysts manual__2024-08-07T14:20:08.695612+00:00 [queued]>
[2024-08-07T14:55:34.688+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow-space-exploration.notify_analysts manual__2024-08-07T14:20:08.695612+00:00 [queued]>
[2024-08-07T14:55:34.689+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-07T14:55:34.717+0000] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): notify_analysts> on 2024-08-07 14:20:08.695612+00:00
[2024-08-07T14:55:34.725+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1630) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-07T14:55:34.727+0000] {standard_task_runner.py:64} INFO - Started process 1638 to run task
[2024-08-07T14:55:34.727+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', '***-space-exploration', 'notify_analysts', 'manual__2024-08-07T14:20:08.695612+00:00', '--job-id', '300', '--raw', '--subdir', 'DAGS_FOLDER/***-space-exploration.py', '--cfg-path', '/tmp/tmpygugr73z']
[2024-08-07T14:55:34.729+0000] {standard_task_runner.py:91} INFO - Job 300: Subtask notify_analysts
[2024-08-07T14:55:34.815+0000] {task_command.py:426} INFO - Running <TaskInstance: airflow-space-exploration.notify_analysts manual__2024-08-07T14:20:08.695612+00:00 [running]> on host 38873943cc86
[2024-08-07T14:55:34.960+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***-space-exploration' AIRFLOW_CTX_TASK_ID='notify_analysts' AIRFLOW_CTX_EXECUTION_DATE='2024-08-07T14:20:08.695612+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-07T14:20:08.695612+00:00'
[2024-08-07T14:55:34.962+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-07T14:55:34.999+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-08-07T14:55:35.000+0000] {configuration.py:1053} WARNING - section/key [smtp/smtp_user] not found in config
[2024-08-07T14:55:35.003+0000] {email.py:271} INFO - Email alerting: attempt 1
[2024-08-07T14:55:35.005+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-07T14:55:35.006+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 273, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 853, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/socket.py", line 838, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2024-08-07T14:55:35.022+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=***-space-exploration, task_id=notify_analysts, run_id=manual__2024-08-07T14:20:08.695612+00:00, execution_date=20240807T142008, start_date=20240807T145534, end_date=20240807T145535
[2024-08-07T14:55:35.048+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 300 for task notify_analysts ([Errno 99] Cannot assign requested address; 1638)
[2024-08-07T14:55:35.103+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-07T14:55:35.139+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-07T14:55:35.144+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
