[2024-08-07T14:09:13.132+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-07T14:09:13.196+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow-space-exploration.Autorizacion_NASA scheduled__2024-08-02T00:00:00+00:00 [queued]>
[2024-08-07T14:09:13.210+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow-space-exploration.Autorizacion_NASA scheduled__2024-08-02T00:00:00+00:00 [queued]>
[2024-08-07T14:09:13.211+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-07T14:09:13.241+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): Autorizacion_NASA> on 2024-08-02 00:00:00+00:00
[2024-08-07T14:09:13.256+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=60) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-07T14:09:13.262+0000] {standard_task_runner.py:64} INFO - Started process 65 to run task
[2024-08-07T14:09:13.262+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', '***-space-exploration', 'Autorizacion_NASA', 'scheduled__2024-08-02T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/***-space-exploration.py', '--cfg-path', '/tmp/tmplamx03bi']
[2024-08-07T14:09:13.264+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask Autorizacion_NASA
[2024-08-07T14:09:13.357+0000] {task_command.py:426} INFO - Running <TaskInstance: airflow-space-exploration.Autorizacion_NASA scheduled__2024-08-02T00:00:00+00:00 [running]> on host 38873943cc86
[2024-08-07T14:09:13.483+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***-space-exploration' AIRFLOW_CTX_TASK_ID='Autorizacion_NASA' AIRFLOW_CTX_EXECUTION_DATE='2024-08-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-02T00:00:00+00:00'
[2024-08-07T14:09:13.485+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-07T14:09:13.609+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-07T14:09:13.612+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "bash_command='sleep 20 && echo 'OK' > /tmp/response_20240802.txt"]
[2024-08-07T14:09:13.638+0000] {subprocess.py:86} INFO - Output:
[2024-08-07T14:09:13.697+0000] {subprocess.py:93} INFO - /usr/bin/bash: -c: line 1: unexpected EOF while looking for matching `''
[2024-08-07T14:09:13.698+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-08-07T14:09:13.702+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-07T14:09:13.717+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-08-07T14:09:13.731+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=***-space-exploration, task_id=Autorizacion_NASA, run_id=scheduled__2024-08-02T00:00:00+00:00, execution_date=20240802T000000, start_date=20240807T140913, end_date=20240807T140913
[2024-08-07T14:09:13.761+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task Autorizacion_NASA (Bash command failed. The command returned a non-zero exit code 2.; 65)
[2024-08-07T14:09:13.800+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-07T14:09:13.836+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-07T14:09:13.842+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
