[2024-08-07T20:33:53.256+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-07T20:33:53.351+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: space_exploration.notify_analysts scheduled__2023-02-11T00:00:00+00:00 [queued]>
[2024-08-07T20:33:53.390+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: space_exploration.notify_analysts scheduled__2023-02-11T00:00:00+00:00 [queued]>
[2024-08-07T20:33:53.396+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-07T20:33:53.894+0000] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): notify_analysts> on 2023-02-11 00:00:00+00:00
[2024-08-07T20:33:53.938+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=444) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-07T20:33:53.961+0000] {standard_task_runner.py:64} INFO - Started process 493 to run task
[2024-08-07T20:33:53.946+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'space_exploration', 'notify_analysts', 'scheduled__2023-02-11T00:00:00+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/***-space-exploration.py', '--cfg-path', '/tmp/tmpsimsghph']
[2024-08-07T20:33:53.968+0000] {standard_task_runner.py:91} INFO - Job 122: Subtask notify_analysts
[2024-08-07T20:33:54.173+0000] {task_command.py:426} INFO - Running <TaskInstance: space_exploration.notify_analysts scheduled__2023-02-11T00:00:00+00:00 [running]> on host 13935ade345d
[2024-08-07T20:33:54.557+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='space_exploration' AIRFLOW_CTX_TASK_ID='notify_analysts' AIRFLOW_CTX_EXECUTION_DATE='2023-02-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-02-11T00:00:00+00:00'
[2024-08-07T20:33:54.570+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-07T20:33:54.695+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-08-07T20:33:54.704+0000] {configuration.py:1053} WARNING - section/key [smtp/smtp_user] not found in config
[2024-08-07T20:33:54.705+0000] {email.py:271} INFO - Email alerting: attempt 1
[2024-08-07T20:33:54.710+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-07T20:33:54.717+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 273, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 853, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/socket.py", line 838, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-08-07T20:33:54.796+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=space_exploration, task_id=notify_analysts, run_id=scheduled__2023-02-11T00:00:00+00:00, execution_date=20230211T000000, start_date=20240807T203353, end_date=20240807T203354
[2024-08-07T20:33:54.883+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 122 for task notify_analysts ([Errno 111] Connection refused; 493)
[2024-08-07T20:33:54.923+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-07T20:33:55.034+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-07T20:33:55.070+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
